apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scanrook
resources:
  - namespace.yaml
  - deployment.yaml
  - dispatcher-deployment.yaml
  - dispatcher-rbac.yaml
  - service.yaml
  - ingress.yaml
  - redis.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - resourcequota.yaml
  - pg-backup-cronjob.yaml
  - hpa.yaml
  - minio-lifecycle-job.yaml
  # - configmap.yaml
  # - secret.yaml
