export type TargetAccountSeed = {
  accountName: string;
  accountDomain: string;
  industry: string;
  companySize: string;
  fitScore: number;
  source: string;
  status: string;
  owner: string;
  nextAction: string;
};

const SOURCE = "starter_public_enterprise_list_v1";
const STATUS = "prospect";
const OWNER = "unassigned";
const NEXT_ACTION = "identify devsecops + compliance contacts";

function seed(
  accountName: string,
  accountDomain: string,
  industry: string,
  companySize: string,
  fitScore = 70,
): TargetAccountSeed {
  return {
    accountName,
    accountDomain,
    industry,
    companySize,
    fitScore,
    source: SOURCE,
    status: STATUS,
    owner: OWNER,
    nextAction: NEXT_ACTION,
  };
}

export const STARTER_TARGET_ACCOUNTS: TargetAccountSeed[] = [
  seed("Verizon", "verizon.com", "Telecommunications", "50000+"),
  seed("AT&T", "att.com", "Telecommunications", "50000+"),
  seed("T-Mobile", "t-mobile.com", "Telecommunications", "10000-50000"),
  seed("Comcast", "comcast.com", "Telecommunications", "50000+"),
  seed("Charter Communications", "charter.com", "Telecommunications", "50000+"),
  seed("Lumen", "lumen.com", "Telecommunications", "10000-50000"),
  seed("IBM", "ibm.com", "Technology", "50000+"),
  seed("Oracle", "oracle.com", "Technology", "50000+"),
  seed("Microsoft", "microsoft.com", "Technology", "50000+"),
  seed("Google", "google.com", "Technology", "50000+"),
  seed("Amazon", "amazon.com", "Technology", "50000+"),
  seed("Meta", "meta.com", "Technology", "50000+"),
  seed("Apple", "apple.com", "Technology", "50000+"),
  seed("Salesforce", "salesforce.com", "Technology", "10000-50000"),
  seed("ServiceNow", "servicenow.com", "Technology", "10000-50000"),
  seed("Adobe", "adobe.com", "Technology", "10000-50000"),
  seed("Cisco", "cisco.com", "Technology", "50000+"),
  seed("VMware", "vmware.com", "Technology", "10000-50000"),
  seed("Palo Alto Networks", "paloaltonetworks.com", "Cybersecurity", "10000-50000"),
  seed("CrowdStrike", "crowdstrike.com", "Cybersecurity", "5000-10000"),
  seed("Fortinet", "fortinet.com", "Cybersecurity", "5000-10000"),
  seed("Okta", "okta.com", "Cybersecurity", "5000-10000"),
  seed("Snowflake", "snowflake.com", "Technology", "5000-10000"),
  seed("Datadog", "datadoghq.com", "Technology", "5000-10000"),
  seed("Cloudflare", "cloudflare.com", "Technology", "1000-5000"),
  seed("Akamai", "akamai.com", "Technology", "5000-10000"),
  seed("JPMorgan Chase", "jpmorganchase.com", "Financial Services", "50000+"),
  seed("Bank of America", "bankofamerica.com", "Financial Services", "50000+"),
  seed("Wells Fargo", "wellsfargo.com", "Financial Services", "50000+"),
  seed("Citigroup", "citi.com", "Financial Services", "50000+"),
  seed("Goldman Sachs", "goldmansachs.com", "Financial Services", "10000-50000"),
  seed("Morgan Stanley", "morganstanley.com", "Financial Services", "10000-50000"),
  seed("Capital One", "capitalone.com", "Financial Services", "10000-50000"),
  seed("American Express", "americanexpress.com", "Financial Services", "10000-50000"),
  seed("Discover", "discover.com", "Financial Services", "10000-50000"),
  seed("PayPal", "paypal.com", "Financial Services", "10000-50000"),
  seed("Visa", "visa.com", "Financial Services", "10000-50000"),
  seed("Mastercard", "mastercard.com", "Financial Services", "10000-50000"),
  seed("FIS", "fisglobal.com", "Financial Services", "10000-50000"),
  seed("Fiserv", "fiserv.com", "Financial Services", "10000-50000"),
  seed("UnitedHealth Group", "unitedhealthgroup.com", "Healthcare", "50000+"),
  seed("CVS Health", "cvshealth.com", "Healthcare", "50000+"),
  seed("Cigna", "cigna.com", "Healthcare", "10000-50000"),
  seed("Elevance Health", "elevancehealth.com", "Healthcare", "50000+"),
  seed("Kaiser Permanente", "kp.org", "Healthcare", "50000+"),
  seed("HCA Healthcare", "hcahealthcare.com", "Healthcare", "10000-50000"),
  seed("Mayo Clinic", "mayoclinic.org", "Healthcare", "50000+"),
  seed("Quest Diagnostics", "questdiagnostics.com", "Healthcare", "10000-50000"),
  seed("Labcorp", "labcorp.com", "Healthcare", "10000-50000"),
  seed("Pfizer", "pfizer.com", "Pharmaceuticals", "50000+"),
  seed("Merck", "merck.com", "Pharmaceuticals", "10000-50000"),
  seed("Johnson & Johnson", "jnj.com", "Pharmaceuticals", "50000+"),
  seed("AbbVie", "abbvie.com", "Pharmaceuticals", "10000-50000"),
  seed("Amgen", "amgen.com", "Pharmaceuticals", "10000-50000"),
  seed("Gilead", "gilead.com", "Pharmaceuticals", "10000-50000"),
  seed("Bristol Myers Squibb", "bms.com", "Pharmaceuticals", "10000-50000"),
  seed("Moderna", "moderna.com", "Pharmaceuticals", "1000-5000"),
  seed("Regeneron", "regeneron.com", "Pharmaceuticals", "10000-50000"),
  seed("Boeing", "boeing.com", "Aerospace", "50000+"),
  seed("Lockheed Martin", "lockheedmartin.com", "Defense", "50000+"),
  seed("Northrop Grumman", "northropgrumman.com", "Defense", "50000+"),
  seed("RTX", "rtx.com", "Defense", "50000+"),
  seed("General Dynamics", "gd.com", "Defense", "10000-50000"),
  seed("Honeywell", "honeywell.com", "Industrial", "50000+"),
  seed("General Electric", "ge.com", "Industrial", "50000+"),
  seed("Delta Air Lines", "delta.com", "Transportation", "50000+"),
  seed("United Airlines", "united.com", "Transportation", "50000+"),
  seed("American Airlines", "aa.com", "Transportation", "50000+"),
  seed("Southwest Airlines", "southwest.com", "Transportation", "50000+"),
  seed("FedEx", "fedex.com", "Transportation", "50000+"),
  seed("UPS", "ups.com", "Transportation", "50000+"),
  seed("Maersk", "maersk.com", "Transportation", "50000+"),
  seed("Walmart", "walmart.com", "Retail", "50000+"),
  seed("Target", "target.com", "Retail", "50000+"),
  seed("Costco", "costco.com", "Retail", "50000+"),
  seed("Home Depot", "homedepot.com", "Retail", "50000+"),
  seed("Lowe's", "lowes.com", "Retail", "50000+"),
  seed("Kroger", "kroger.com", "Retail", "50000+"),
  seed("Walgreens Boots Alliance", "walgreensbootsalliance.com", "Retail", "50000+"),
  seed("PepsiCo", "pepsico.com", "Consumer Goods", "50000+"),
  seed("Coca-Cola", "coca-colacompany.com", "Consumer Goods", "50000+"),
  seed("Procter & Gamble", "pg.com", "Consumer Goods", "50000+"),
  seed("Unilever", "unilever.com", "Consumer Goods", "50000+"),
  seed("Nestle", "nestle.com", "Consumer Goods", "50000+"),
  seed("Tesla", "tesla.com", "Automotive", "50000+"),
  seed("Ford", "ford.com", "Automotive", "50000+"),
  seed("General Motors", "gm.com", "Automotive", "50000+"),
  seed("Toyota", "toyota.com", "Automotive", "50000+"),
  seed("Honda", "honda.com", "Automotive", "50000+"),
  seed("BMW Group", "bmwgroup.com", "Automotive", "50000+"),
  seed("Shell", "shell.com", "Energy", "50000+"),
  seed("ExxonMobil", "exxonmobil.com", "Energy", "50000+"),
  seed("Chevron", "chevron.com", "Energy", "50000+"),
  seed("BP", "bp.com", "Energy", "50000+"),
  seed("ConocoPhillips", "conocophillips.com", "Energy", "10000-50000"),
  seed("Siemens", "siemens.com", "Industrial", "50000+"),
  seed("Schneider Electric", "se.com", "Industrial", "50000+"),
  seed("ABB", "abb.com", "Industrial", "50000+"),
  seed("Intel", "intel.com", "Semiconductors", "50000+"),
  seed("AMD", "amd.com", "Semiconductors", "10000-50000"),
];

