apiVersion: v1
kind: Service
metadata:
  name: scanrook-dispatcher
  labels:
    app: scanrook-dispatcher
spec:
  type: ClusterIP
  selector:
    app: scanrook-dispatcher
  ports:
    - name: http
      port: 8080
      targetPort: 8080
