apiVersion: v1
kind: Service
metadata:
  name: deltaguard-web
  labels:
    app: deltaguard-web
spec:
  type: ClusterIP
  selector:
    app: deltaguard-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000


