import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { APP_NAME } from "@/lib/brand";
import { isPublished } from "@/lib/publishGate";

export const revalidate = 3600;
const PUBLISH_DATE = "2026-12-19";

const title = `Software Provenance: What It Is and Why It Matters | ${APP_NAME}`;
const description =
  "Software provenance is verifiable evidence of where a build artifact came from and how it was built. How SLSA and in-toto attestations work, and why it matters.";

export const metadata: Metadata = {
  title,
  description,
  keywords: [
    "software provenance",
    "provenance attestation",
    "build provenance",
    "slsa provenance",
    "in-toto attestation",
    "supply chain provenance",
    "artifact provenance",
    "npm provenance",
    "provenance vs sbom",
    "verifiable build",
  ],
  alternates: { canonical: "/blog/software-provenance" },
  openGraph: {
    title,
    description,
    type: "article",
    url: "/blog/software-provenance",
    images: ["/blog/software-provenance.jpg"],
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    images: ["/blog/software-provenance.jpg"],
  },
};

const articleJsonLd = {
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  headline: "Software Provenance: What It Is and Why It Matters",
  description,
  author: { "@type": "Organization", name: "ScanRook" },
  publisher: { "@type": "Organization", name: "ScanRook" },
  mainEntityOfPage: "https://scanrook.io/blog/software-provenance",
  image: "https://scanrook.io/blog/software-provenance.jpg",
  datePublished: PUBLISH_DATE,
  dateModified: PUBLISH_DATE,
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is software provenance?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Software provenance is verifiable evidence describing where a build artifact came from and how it was produced: the source repository and commit, the build system that ran, the inputs it consumed, and who or what triggered it. It is usually expressed as a signed attestation attached to the artifact, so a consumer can confirm the artifact was built from the claimed source by the claimed builder rather than substituted or tampered with.",
      },
    },
    {
      "@type": "Question",
      name: "How is provenance different from an SBOM?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "An SBOM answers what is inside an artifact: the list of components and their versions. Provenance answers where the artifact came from and how it was built. They are complementary. An SBOM without provenance tells you the ingredients but not whether the package on your shelf is the one the vendor actually made; provenance without an SBOM proves the origin but not the contents. Mature supply-chain programs produce both.",
      },
    },
    {
      "@type": "Question",
      name: "What is a SLSA provenance attestation?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "SLSA (Supply-chain Levels for Software Artifacts) defines a provenance format and a set of build levels. A SLSA provenance attestation is a signed document, typically in the in-toto format, that records the build's source, builder identity, build parameters, and materials. Higher SLSA build levels require the provenance to be generated by a hardened, isolated build platform the developer cannot tamper with, which raises the trust you can place in it.",
      },
    },
    {
      "@type": "Question",
      name: "How do I generate provenance for my builds?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "The most common path today is CI-generated provenance. GitHub Actions offers the attest-build-provenance action to produce and sign a SLSA provenance attestation for any artifact, npm publish supports a --provenance flag for packages built in supported CI, and Sigstore Cosign can sign and attach attestations to container images. Each records the build context automatically and stores the signature so downstream consumers can verify it.",
      },
    },
    {
      "@type": "Question",
      name: "Does provenance replace vulnerability scanning?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No. Provenance proves an artifact is authentic and was built the way it claims, but an authentic build can still contain a vulnerable dependency. Provenance and scanning answer different questions: is this the real thing, and is the real thing safe. You verify provenance to trust the origin, then scan the verified artifact to find known vulnerabilities in the components it actually contains.",
      },
    },
  ],
};

export default function Page() {
  if (!isPublished({ publishDate: PUBLISH_DATE })) notFound();
  return (
    <main className="mx-auto max-w-3xl px-6 py-14 grid gap-6">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />

      <article className="surface-card p-8 grid gap-6">
        <header className="grid gap-3">
          <div className="text-xs uppercase tracking-wide muted">Security Concepts</div>
          <h1 className="text-3xl font-semibold tracking-tight">
            Software Provenance: What It Is and Why It Matters
          </h1>
          <p className="text-sm muted">Published December 19, 2026 &middot; 8 min read</p>
          <p className="text-sm muted">
            Software provenance is the verifiable record of where a build artifact came from and how
            it was produced. In a world where attackers increasingly target the build pipeline rather
            than the running application, provenance is what lets you answer a deceptively simple
            question: is this binary really the one my source code produced? Here is what provenance
            records, the standards that define it, and where it fits alongside SBOMs and scanning.
          </p>
        </header>

        <img
          src="/blog/software-provenance.jpg"
          alt="Software provenance: verifiable build origin"
          className="w-full rounded-xl border border-black/10 dark:border-white/10"
        />

        <section className="grid gap-3">
          <h2 className="text-xl font-semibold tracking-tight">What provenance actually means</h2>
          <p className="text-sm muted">
            Provenance is a term borrowed from the art world, where it describes the documented
            chain of custody that proves a painting is genuine. In software, provenance is the same
            idea applied to artifacts: the container image, JAR, wheel, or binary you are about to
            ship or install. A provenance record answers questions like <em>which git commit was
            this built from</em>, <em>what build system produced it</em>, <em>what inputs did that
            build consume</em>, and <em>who triggered it</em> &mdash; and it does so in a way a
            machine can verify cryptographically rather than trust on faith.
          </p>
          <p className="text-sm muted">
            The reason this matters is the shift in where attacks land. Compromising a single
            dependency, a build server, or a CI token lets an attacker inject malicious code into an
            artifact that still carries a trusted name and version. The SolarWinds and Codecov
            incidents both worked this way: the published artifact did not match the reviewed source.
            Provenance is the countermeasure &mdash; it binds the artifact to its build so a
            substitution is detectable. It is a core building block of{" "}
            <Link href="/blog/software-supply-chain-security" className="underline">
              software supply chain security
            </Link>
            .
          </p>
        </section>

        <section className="grid gap-3">
          <h2 className="text-xl font-semibold tracking-tight">Provenance vs SBOM: two different questions</h2>
          <p className="text-sm muted">
            Provenance is often confused with a Software Bill of Materials, but they answer
            different questions and are strongest together. An{" "}
            <Link href="/blog/what-is-sbom-and-how-scanrook-uses-it" className="underline">
              SBOM
            </Link>{" "}
            is an inventory: it lists the components inside an artifact and their versions.
            Provenance is a pedigree: it records where the artifact came from and how it was built.
            An SBOM tells you the ingredients; provenance tells you the artifact on your shelf is the
            one the vendor actually made, in the kitchen they claim, from the recipe you reviewed.
          </p>
          <p className="text-sm muted">
            You need both because each covers the other&apos;s blind spot. An SBOM with no
            provenance can be forged along with the artifact it describes. Provenance with no SBOM
            proves the origin but leaves you blind to a vulnerable transitive dependency baked into a
            genuine build. If you are already reading{" "}
            <Link href="/blog/how-to-read-sbom" className="underline">
              SBOMs
            </Link>
            , provenance is the natural next layer.
          </p>
        </section>

        <section className="grid gap-3">
          <h2 className="text-xl font-semibold tracking-tight">The provenance flow</h2>
          <p className="text-sm muted">
            At a high level, provenance is generated by the build, signed, and verified by whoever
            consumes the artifact. The build platform is the trust anchor: it observes the source and
            inputs directly, so its statement about them is more credible than one a developer types
            by hand.
          </p>
          <div className="overflow-x-auto surface-card p-4">
            <svg
              viewBox="0 0 820 220"
              role="img"
              aria-label="Provenance flow from source commit through a build platform to a signed attestation verified by the consumer"
              className="w-full h-auto text-black dark:text-white"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect width="820" height="220" rx="16" className="fill-black/[.02] dark:fill-white/[.02]" />

              <rect x="24" y="80" width="150" height="60" rx="10" className="fill-black/[.05] dark:fill-white/[.08] stroke-black/10 dark:stroke-white/10" strokeWidth="1" />
              <text x="99" y="106" textAnchor="middle" className="fill-current" fontSize="12" fontWeight="600">Source</text>
              <text x="99" y="124" textAnchor="middle" className="fill-current" fontSize="10" opacity="0.6">git commit + inputs</text>

              <line x1="174" y1="110" x2="238" y2="110" className="stroke-current" strokeWidth="1.5" opacity="0.4" markerEnd="url(#arrow)" />

              <rect x="240" y="70" width="180" height="80" rx="10" className="fill-[var(--dg-accent,#2563eb)]" opacity="0.06" />
              <rect x="240" y="70" width="180" height="80" rx="10" className="stroke-[var(--dg-accent,#2563eb)]" strokeWidth="2" fill="none" />
              <text x="330" y="100" textAnchor="middle" className="fill-current" fontSize="12" fontWeight="600">Build platform</text>
              <text x="330" y="118" textAnchor="middle" className="fill-current" fontSize="10" opacity="0.6">records build context,</text>
              <text x="330" y="132" textAnchor="middle" className="fill-current" fontSize="10" opacity="0.6">emits + signs provenance</text>

              <line x1="420" y1="110" x2="484" y2="110" className="stroke-current" strokeWidth="1.5" opacity="0.4" markerEnd="url(#arrow)" />

              <rect x="486" y="80" width="150" height="60" rx="10" className="fill-black/[.05] dark:fill-white/[.08] stroke-black/10 dark:stroke-white/10" strokeWidth="1" />
              <text x="561" y="102" textAnchor="middle" className="fill-current" fontSize="12" fontWeight="600">Artifact</text>
              <text x="561" y="120" textAnchor="middle" className="fill-current" fontSize="10" opacity="0.6">+ signed attestation</text>

              <line x1="636" y1="110" x2="700" y2="110" className="stroke-current" strokeWidth="1.5" opacity="0.4" markerEnd="url(#arrow)" />

              <rect x="702" y="80" width="94" height="60" rx="10" className="fill-black/[.05] dark:fill-white/[.08] stroke-black/10 dark:stroke-white/10" strokeWidth="1" />
              <text x="749" y="102" textAnchor="middle" className="fill-current" fontSize="12" fontWeight="600">Consumer</text>
              <text x="749" y="120" textAnchor="middle" className="fill-current" fontSize="10" opacity="0.6">verifies</text>

              <text x="410" y="40" textAnchor="middle" className="fill-current" fontSize="11" opacity="0.55">Provenance binds the artifact to the build that produced it</text>

              <defs>
                <marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto">
                  <path d="M0,0 L6,3 L0,6 Z" className="fill-current" opacity="0.5" />
                </marker>
              </defs>
            </svg>
          </div>
        </section>

        <section className="grid gap-3">
          <h2 className="text-xl font-semibold tracking-tight">What a provenance attestation records</h2>
          <p className="text-sm muted">
            A provenance attestation is a structured, signed statement about an artifact. The exact
            fields depend on the format, but the common core is:
          </p>
          <ul className="text-sm muted list-disc pl-5 grid gap-1.5">
            <li>
              <strong>Subject.</strong> The artifact the statement is about, identified by a
              cryptographic digest (for example the SHA-256 of a container image) rather than a
              mutable tag.
            </li>
            <li>
              <strong>Builder identity.</strong> Which build platform produced it &mdash; a specific
              GitHub Actions workflow, a Google Cloud Build trigger, a self-hosted runner.
            </li>
            <li>
              <strong>Build definition.</strong> The source repository and commit, the entry point
              or workflow file, and the parameters the build ran with.
            </li>
            <li>
              <strong>Materials / resolved dependencies.</strong> The inputs the build consumed,
              ideally pinned by digest so the record is reproducible.
            </li>
            <li>
              <strong>Metadata.</strong> Timestamps and, at higher assurance levels, whether the
              build was isolated and non-falsifiable.
            </li>
          </ul>
          <p className="text-sm muted">
            Because the whole document is signed and the subject is a digest, changing the artifact
            invalidates the attestation. That is the property that makes provenance useful: a
            tampered or substituted artifact cannot present valid provenance for itself.
          </p>
        </section>

        <section className="grid gap-3">
          <h2 className="text-xl font-semibold tracking-tight">SLSA: levels of build assurance</h2>
          <p className="text-sm muted">
            SLSA &mdash; Supply-chain Levels for Software Artifacts, an OpenSSF project &mdash; is
            the framework most teams reach for when they formalize provenance. SLSA defines both a
            provenance format and a ladder of build levels that describe <em>how trustworthy the
            provenance itself is</em>. The distinction matters: provenance a developer can quietly
            edit is worth far less than provenance generated by an isolated platform the developer
            cannot reach into.
          </p>
          <p className="text-sm muted">
            In the current v1.0 track, Build Level 1 means provenance exists and describes the build.
            Build Level 2 requires it to be generated by a hosted build platform and signed. Build
            Level 3 adds hardening so the build is isolated and the provenance is
            non-forgeable even by the project&apos;s own maintainers. Higher levels do not make your
            code more secure; they make the <em>claim</em> about how it was built harder to fake. We
            cover the full ladder in{" "}
            <Link href="/blog/slsa-framework-explained" className="underline">
              the SLSA framework explained
            </Link>
            .
          </p>
        </section>

        <section className="grid gap-3">
          <h2 className="text-xl font-semibold tracking-tight">in-toto: the attestation format underneath</h2>
          <p className="text-sm muted">
            SLSA describes what to record; in-toto is the format that carries it. in-toto is a
            CNCF-graduated framework for attestations about steps in a supply chain. Its attestation
            spec defines a simple envelope: a statement with a type, a subject (the artifact digest),
            and a predicate (the actual claim &mdash; for provenance, the SLSA provenance predicate).
            The envelope is wrapped in a DSSE signature so it can be verified independently of where
            it is stored.
          </p>
          <p className="text-sm muted">
            The value of a shared format is that tools interoperate. A build platform emits an
            in-toto SLSA provenance predicate, a signing tool wraps and signs it, a registry stores
            it next to the image, and a policy engine at deploy time verifies it &mdash; none of
            which need to be from the same vendor. Provenance, SBOMs, and test results can all ride
            the same envelope, which is why in-toto has become the connective tissue of the
            supply-chain tooling ecosystem.
          </p>
        </section>

        <section className="grid gap-3">
          <h2 className="text-xl font-semibold tracking-tight">Generating and verifying provenance in practice</h2>
          <p className="text-sm muted">
            You do not have to build this from scratch. Several mainstream paths generate signed
            provenance with a few lines of configuration:
          </p>
          <ul className="text-sm muted list-disc pl-5 grid gap-1.5">
            <li>
              <strong>GitHub Actions.</strong> The <code className="text-xs rounded bg-black/[.06] dark:bg-white/[.06] px-1.5 py-0.5">actions/attest-build-provenance</code>{" "}
              action produces and signs a SLSA provenance attestation for any artifact your workflow
              builds, using the workflow identity and Sigstore for keyless signing.
            </li>
            <li>
              <strong>npm.</strong> Running <code className="text-xs rounded bg-black/[.06] dark:bg-white/[.06] px-1.5 py-0.5">npm publish --provenance</code>{" "}
              from a supported CI provider attaches a public provenance attestation to the package,
              visible on the npm registry.
            </li>
            <li>
              <strong>Sigstore Cosign.</strong> Cosign can sign container images and attach
              attestations, storing signatures in the registry and a transparency log. It is the
              same tooling covered in{" "}
              <Link href="/blog/sigstore-cosign-container-signing" className="underline">
                image signing with Sigstore and Cosign
              </Link>
              .
            </li>
          </ul>
          <p className="text-sm muted">
            Generating provenance is only half the loop &mdash; it is worthless if nobody checks it.
            Verification belongs at the boundary where you consume the artifact: a Kubernetes
            admission controller that rejects images lacking valid provenance, a deploy step that
            runs <code className="text-xs rounded bg-black/[.06] dark:bg-white/[.06] px-1.5 py-0.5">cosign verify-attestation</code>, or a policy engine
            evaluating the SLSA predicate against a rule such as &ldquo;built from the main branch of
            our repo by our CI.&rdquo; Provenance you generate but never verify is documentation, not
            a control.
          </p>
        </section>

        <section className="grid gap-3">
          <h2 className="text-xl font-semibold tracking-tight">Where provenance ends and scanning begins</h2>
          <p className="text-sm muted">
            Provenance and vulnerability scanning are often bundled under &ldquo;supply-chain
            security,&rdquo; but they defend against different failures, and it is worth being precise
            about the seam. Provenance proves an artifact is authentic and was built the way it
            claims. It says nothing about whether that authentic artifact is <em>safe</em>: a
            perfectly genuine build, correctly attested at SLSA Build Level 3, can still ship a
            critical CVE in a bundled library.
          </p>
          <p className="text-sm muted">
            That is where ScanRook fits, and we are deliberate about the boundary: ScanRook does not
            generate provenance for you &mdash; your CI platform does that. What ScanRook does is
            scan the artifact you have decided to trust, reading the actual package databases inside
            a container and matching installed components against OSV, NVD, and vendor advisory data.
            The healthy pattern is sequential: verify provenance to establish that you have the real
            artifact, then scan the real artifact to learn what is inside it and what needs patching.
            One control answers <em>is this genuine</em>; the other answers <em>is this genuine thing
            safe to run</em>.
          </p>
        </section>

        <section className="grid gap-4">
          <h2 className="text-xl font-semibold tracking-tight">Frequently asked questions</h2>
          <div className="grid gap-4">
            <div>
              <h3 className="text-sm font-semibold">What is software provenance?</h3>
              <p className="text-sm muted mt-1">
                Verifiable evidence of where an artifact came from and how it was built &mdash; the
                source commit, build system, inputs, and trigger &mdash; usually as a signed
                attestation attached to the artifact.
              </p>
            </div>
            <div>
              <h3 className="text-sm font-semibold">How is provenance different from an SBOM?</h3>
              <p className="text-sm muted mt-1">
                An SBOM lists what is inside an artifact; provenance records where it came from and
                how it was built. They are complementary, and mature programs produce both.
              </p>
            </div>
            <div>
              <h3 className="text-sm font-semibold">What is a SLSA provenance attestation?</h3>
              <p className="text-sm muted mt-1">
                A signed in-toto document recording an artifact&apos;s source, builder identity, and
                build parameters. Higher SLSA build levels require it to come from a hardened,
                tamper-resistant build platform.
              </p>
            </div>
            <div>
              <h3 className="text-sm font-semibold">Does provenance replace vulnerability scanning?</h3>
              <p className="text-sm muted mt-1">
                No. Provenance proves an artifact is authentic; scanning finds vulnerable components
                inside it. An authentic build can still contain a critical CVE, so you need both.
              </p>
            </div>
          </div>
        </section>

        <section className="mt-2 rounded-xl bg-[var(--dg-accent,#2563eb)]/[.06] border border-[var(--dg-accent,#2563eb)]/20 p-5 grid gap-3">
          <h3 className="text-sm font-semibold">Verify the origin, then scan the artifact</h3>
          <p className="text-sm muted leading-relaxed">
            Provenance tells you an artifact is genuine. ScanRook tells you what is inside it &mdash;
            matching installed packages against OSV, NVD, and vendor advisories so a genuine build
            with a hidden CVE does not reach production unnoticed.
          </p>
          <div className="flex gap-3">
            <Link
              href="/dashboard"
              className="rounded-lg bg-[var(--dg-accent,#2563eb)] text-white px-4 py-2 text-sm font-medium"
            >
              Start scanning
            </Link>
            <Link href="/docs" className="btn-secondary">Read the docs</Link>
          </div>
        </section>

        <footer className="border-t border-black/10 dark:border-white/10 pt-4 text-xs muted grid gap-2">
          <p>
            <strong>Related reading:</strong>{" "}
            <Link href="/blog/slsa-framework-explained" className="underline">
              The SLSA Framework Explained
            </Link>{" "}
            &middot;{" "}
            <Link href="/blog/software-supply-chain-security" className="underline">
              Software Supply Chain Security
            </Link>{" "}
            &middot;{" "}
            <Link href="/blog/sigstore-cosign-container-signing" className="underline">
              Image Signing with Sigstore and Cosign
            </Link>
          </p>
        </footer>
      </article>
    </main>
  );
}
