INSERT INTO content_calendar_meta (slug, keyword, difficulty, monthly_volume)
VALUES
('aws-inspector','aws inspector',0,1600),
('mtls-mutual-tls','mtls',15,5400),
('nikto-web-scanner','nikto',17,4400),
('disa-stig','disa stig',22,4400),
('brakeman-rails-security','brakeman',11,2900),
('aws-guardduty','aws guardduty',3,2400),
('fips-140-2','fips 140-2',22,2400),
('tetragon','tetragon',27,2900),
('kustomize-security','kustomize',24,1900),
('skopeo','skopeo',2,1600),
('open-policy-agent','open policy agent',5,1600),
('yara-rules','yara rules',25,1300),
('buildah','buildah',18,880),
('sigma-rules','sigma rules',21,880),
('dependency-track','dependency track',11,720),
('buildkit-security','buildkit',21,720),
('policy-as-code','policy as code',11,590),
('dirty-cow','dirty cow',8,480),
('owasp-asvs','owasp asvs',12,480),
('flux-cd-security','flux cd',18,480),
('docker-scout','docker scout',17,390),
('spotbugs','spotbugs',14,320),
('sbom-tools','sbom tools',11,320),
('artifact-registry','artifact registry',20,320),
('kubernetes-rbac','kubernetes rbac',16,320),
('printnightmare','printnightmare',22,320),
('kubescape','kubescape',20,260),
('opa-gatekeeper','opa gatekeeper',14,260),
('dirty-pipe','dirty pipe',22,260),
('nuclei-scanner','nuclei scanner',3,260),
('mitre-d3fend','mitre d3fend',6,260),
('kev-catalog','kev catalog',17,260),
('bandit-python','bandit python',12,210),
('gosec','gosec',9,210),
('immutable-infrastructure','immutable infrastructure',7,210),
('cilium-network-policy','cilium network policy',8,210),
('dockerfile-best-practices','dockerfile best practices',22,170),
('kubernetes-security-best-practices','kubernetes security best practices',19,170),
('pwnkit','pwnkit',18,170),
('follina','follina',13,140),
('sops-secrets','sops secrets',16,140),
('aks-security','aks security',0,170),
('private-registry-security','private registry',22,110),
('cve-numbering-authority','cve numbering authority',21,70),
('vulnerability-prioritization','vulnerability prioritization',0,140),
('github-actions-security','github actions security',23,70),
('continuous-compliance','continuous compliance',0,140),
('helm-security','helm security',0,140),
('container-escape','container escape',4,90),
('ebpf-security','ebpf security',20,50),
('image-promotion','image promotion',0,90),
('secret-rotation','secret rotation',6,70),
('image-pull-secrets','image pull secrets',11,70),
('ci-cd-security-best-practices','ci cd security best practices',9,70),
('red-hat-security-advisories','red hat security advisories',13,50),
('bundler-audit','bundler audit',0,50),
('lambda-security','lambda security',0,50),
('kubernetes-admission-controller','admission controller kubernetes',1,50)
ON CONFLICT (slug) DO UPDATE SET
  keyword = EXCLUDED.keyword,
  difficulty = EXCLUDED.difficulty,
  monthly_volume = EXCLUDED.monthly_volume,
  updated_at = now();
