FROM python:3.12-slim

RUN pip install --no-cache-dir \
    psycopg2-binary \
    requests \
    zstandard \
    minio

COPY vulndb-pg-import.py /app/vulndb-pg-import.py

WORKDIR /app
ENTRYPOINT ["python3", "vulndb-pg-import.py"]
